datasets:
- lcw99/wikipedia-korean-20240501-1million-qna
- MarkrAI/KoCommercial-Dataset
- maywell/koVast
models:
- Llama-3.2-1B-Instruct-bf16
- Josiefied-Qwen3-0.6B-abliterated-v1-bf16
- gemma-3-1b-it-qat-4bit
